### PR TITLE
WIP fix broken jdownloader actions

### PR DESCRIPTION
**Pull request by rix1337**
@causefx  this is WIP - I have not yet figured out why the actions from function.js are not working with organizr-functions.php

### CODE REVIEW

**Comment by causefx** [comment]
this one isnt ready yet?

**Comment by rix1337** [comment]
@causefx no. Didn't figure it out yet

**Comment by causefx** [comment]
@rix1337 the actions worked before or they are new?

**Comment by rix1337** [comment]
they all worked when first implemented. my first pr was years ago. i basically copy pasted the qbittorrent commands for start/stop downloads and had them working

they dont now.

would be okay, if you removed them - superb if they started working again.

**Pull request closed without merging**
