### PR TITLE
[Homepage] JDownloader integration

### PR DESCRIPTION
**Pull request by rix1337**
This closes causefx#962

Requires my Python `myjd-api` package. https://pypi.org/project/myjd-api/

This includes
- Settings
- API check
- Running downloads (package name, download speed, filesize, percentage)
- Packages in linkgrabber (package name -> list in "history tab")
- integration with combined downloader

itworks

### CODE REVIEW

**Comment by rix1337** [comment]
I will look into enabling the Start/Stop button as well.

**Comment by causefx** [comment]
I'm switching this to dev branch.  I will merge there :)

**Comment by rix1337** [comment]
Cool! I wanted to build this upon the stable branch, thats why I branched out from master.
Will send future PRs directly to the dev branch.

**Comment by causefx** [comment]
Awesome! Sounds good.So far no issues.  I'm glad you were able to read the code well.  Did ya just search for sab and go from there?

**Comment by rix1337** [comment]
Yup and I never did anything substantial in PHP before. 😄

The whole thing was very readable and easy to follow. I basically copy/pasted the sabnzbd functions and went from there.

That's why I placed the new functions very close to sab.

Most time was spent on setting up PhpStorm and especially the debugger to get those arrays straight.

**Comment by rix1337** [comment]
Was a a great experience getting to understand this project better.
`myjd_api` also offers Start/Stop/Update functionality for JDownloader. I might add these as well in the following weeks.

**Comment by rix1337** [comment]
Also might add some sort of Token to https://pypi.org/project/myjd-api/ in the future, because `http://USER:PASS@host:9090` did not seem to work.

**Comment by causefx** [comment]
ahh that makes sense.  Either way, i'm glad you got it sorted.

**Comment by causefx** [comment]
Also, I will add a note on this homepage item that it requires your python module.

image

**Comment by rix1337** [comment]
Thanks very much.

If you run into any issue running the python module, I'll open an issue at https://github.com/rix1337/MyJD-API

**Comment by causefx** [comment]
@rix1337 do you plan on creating a docker image for the python module for peeps that want it?

**Comment by rix1337** [comment]
Oh, thats a great and very obvious idea.

Will do tonight ;)

**Comment by rix1337** [comment]
The script needs a few tweaks ported over from RSScrawler to make this work in docker. This should not take long

**Comment by causefx** [comment]
no worries.  thanks man. i appreciate it.

**Comment by rix1337** [comment]
Done: https://cloud.docker.com/repository/docker/rix1337/docker-myjd-api/general

**Comment by rix1337** [comment]
Done: https://hub.docker.com/r/rix1337/docker-myjd-api

**Comment by causefx** [comment]
nice. thanks man. i will add to organizr docs website

**Comment by rix1337** [comment]
glad you find this useful. there might be some bugs with this standalone version, as its been only tested by me, but the api itself is quite stable.. its been in use by various people in my main project RSScrawler for a while.

**Comment by rix1337** [comment]
thx for the quick update release

**Pull request merged**
