### PR TITLE
Montiorr homepage item bugfix

### PR DESCRIPTION
**Pull request by henrywhitaker3**
Some monitorr instances don't put `style="cursor: default"` so have accounted for that

### CODE REVIEW

**Comment by causefx** [comment]
you could also just use class `mouse`

**Comment by henrywhitaker3** [comment]
What do you mean?

**Comment by causefx** [comment]
sorry that was vague - 
```
<element class="mouse">yup</element>
```

**Comment by henrywhitaker3** [comment]
I'm not adding the `style="cursor: default"` to anything in the front-end.

The output of the monitorr page I'm scraping outputs either:

```html
<div id="servicetitleoffline" style="cursor: default"><div>SERVICE</div></div><div class="btnoffline" style="cursor: default">Offline</div></div></div>
```

or 

```html
<div id="servicetitleoffline"><div>SERVICE</div></div><div class="btnoffline">Offline</div></div></div>
```

so have altered the regex patterns to match `.*` instead of `style="cursor: default;"` so that both scenarioes are accounted for.

**Comment by causefx** [comment]
LOL - my bad... I just read your first comment briefly - didnt check the code lol... my bad again

**Comment by henrywhitaker3** [comment]
Haha no worries

**Pull request merged**
