### PR TITLE
Add uTorrent Homepage Item

### PR DESCRIPTION
**Pull request by TehMuffinMoo**
Hey,

This is just a quick PR for a new uTorrent Homepage item, it supports both uTorrent & BitTorrent.

I also noticed there's an outstanding [Feature Request](https://vote.organizr.app/suggestions/150893/utorrent-support) for it, so may be closed if you're happy with it.

### CODE REVIEW

**Comment by TehMuffinMoo** [comment]
image

**Comment by causefx** [comment]
sweet -  i will check this out today

**Comment by causefx** [comment]
does the uTorrent Token change often?

**Comment by TehMuffinMoo** [comment]
Not particuarly frequently from what I can tell, only on BitTorrent/uTorrent restart.

The documentation for their token system was awful but it gives a handy breakdown of when the token expires;

https://github.com/bittorrent/webui/wiki/TokenSystem

As we're retaining the GUID cookie, the connection should persist and maintain the token also.

Thanks!

**Pull request merged**
