### PR TITLE
Added uptime kuma homepage item

### PR DESCRIPTION
**Pull request by henrywhitaker3**
Added  a homepage item to display uptime kuma monitors

A bit hacky as it has to parse prometheus metrics to get the data as there's no API for uptime kuma

image

### CODE REVIEW

**Comment by robson90** [comment]
@causefx is it possible to build a new version, with this additon ?

**Comment by causefx** [comment]
damn i havent merged into master - i will do that

**Comment by causefx** [comment]
life is hectic lol

**Comment by causefx** [comment]
completed in #1952 - thanks @robson90

**Pull request merged**
