### PR TITLE
Add missing slash to error.php URLs

### PR DESCRIPTION
**Pull request by nemchik**
I found that when accessing Organizr and having authentication required on the homepage I am given a 404 error from my web server (nginx) but the expected behaviour is to be prompted to login. After reviewing the developer console I fould my browser being redirected to /organizrerror.php?error=999 instead of /organizr/error.php?error=999 so this PR resolves that issue.

### CODE REVIEW

**Comment by causefx** [comment]
are you on windows?

**Comment by causefx** [comment]
Im in the process of changing this functions.php file, i will add it in.

**Comment by nemchik** [comment]
I run Organizr on Ubuntu, not Windows. I get the error in various browsers, including Chrome on Android and Chrome on Windows.

**Comment by causefx** [comment]
do you run it in a directory and not root?

**Comment by nemchik** [comment]
Yes. I run it like http://ddns.host/organizr

**Comment by nemchik** [comment]
So now that you bring that up, this would be a more appropriate change:

```
		if ($GLOBALS['USER']->authenticated) {
			header('Location: '.rtrim(dirname($_SERVER['SCRIPT_NAME']), '/').'/error.php?error=401');
			echo '<script>window.location.href = \''.rtrim(dirname($_SERVER['SCRIPT_NAME']), '/').'/error.php?error=401\'</script>';
		} else {
			header('Location: '.rtrim(dirname($_SERVER['SCRIPT_NAME']), '/').'/error.php?error=999');
			echo '<script>window.location.href = \''.rtrim(dirname($_SERVER['SCRIPT_NAME']), '/').'/error.php?error=999\'</script>';
		}
```

**Comment by causefx** [comment]
I'll add it in.  Thanks!

**Pull request closed without merging**
