### PR TITLE
Added toggle to display title on Pi-hole and Tautulli homepage items

### PR DESCRIPTION
**Pull request by henrywhitaker3**

### CODE REVIEW

**Comment by jscottelblein** [comment]
Awesome. It seems to only have an effect if you only have 1 PH though; if you have 2 the labels will still show.

**Comment by henrywhitaker3** [comment]
Working fine for me:

pihole-no-title

vs

pihole-with-title

**Comment by jscottelblein** [comment]
The screenshot show only 1 Pi-hole though, no?

That's what I was referring to; it works fine w/only 1, but if you have more than 1, the labels still show. I have 2 Pi-holes running on 2 diff machines.

Here's mine.

In the vid I toggle it off, then nav to the homepage and the labels are still there, Then I do a regular refresh, and they're still there, and as a final confirmation, I do a ctrl+f5 refresh to clear the cache first, and the labels are still there.

Pi-hole

**Comment by HalianElf** [comment]
That was with two using the combined cards. Is one of your Piholes in Organizr as "pihole"? That's showing which one is which. Like this is mine separated.
image

**Comment by jscottelblein** [comment]
@HalianElf 

> That was with two using the combined cards.

Ahh, good eye. I didn't look close enough to notice that. I haven't tried combining them in mine yet. So far I still like them separate.

> Is one of your Piholes in Organizr as "pihole"? That's showing which one is which. Like this is mine separated.

Yes, the PH on a PC of mine is just named "Pihole", while the 2nd PH on my Pi is shown as it's IP.

**Comment by HalianElf** [comment]
Yea so the title is hidden, it just has the label for your PiHole shown. Otherwise it'd look something like this: 
image

**Comment by jscottelblein** [comment]
@HalianElf 

hmmm, where do I set the titles/labels of each PH?

**Comment by henrywhitaker3** [comment]
The labels come form the IP/hostname you set in the connection settings, so `http://10.0.0.1/admin` -> `10.0.0.1` for the label

**Comment by henrywhitaker3** [comment]
Gonna submit a PR moving the IP/host label to inside the card so it's more consistent with the hide title bit:

pihole-with-title

**Comment by jscottelblein** [comment]
@henrywhitaker3 

> The labels come form the IP/hostname you set in the connection settings, so `http://10.0.0.1/admin` -> `10.0.0.1` for the label

I was thinking that might be it, while going through the settings. =)

That fix sounds perfect. Thanks!

**Pull request merged**
