### PR TITLE
German Translation

### PR DESCRIPTION
**Pull request by rix1337**
Watch out for umlauts and possible missing strings (e.g. Previous/Next in Info log)

### CODE REVIEW

**Comment by causefx** [comment]
Part of #64 

Also @rix1337 Someone on Reddit also did German:

```
WELCOME = "Willkommen"
OPTIONS = "Optionen"
EDIT_INFO = "Infos ändern"
UPDATE = "Update"
GO_BACK = "Zurück"
LOGOUT = "Logout"
LOGIN = "Login"
DO_YOU_WANT_TO_LOGOUT = "Möchtest Du dich ausloggen?"
YES_WORD = "Ja"
NO_WORD = "Nein"
EMAIL_ADDRESS = "E-mail Addresse"
EMAIL = "E-mail"
PASSWORD = "Passwort"
PASSWORD_AGAIN = "Passwort bestätigen"
ADMIN = "Admin"
USER = "Benutzer"
HOLD_UP = "Warte!"
OOKS_LIKE_YOU_DONT_HAVE_ACCESS = "Anscheinend hast Du keinen Zutritt."
USERNAME = "Benutzername"
REMEMBER_ME = "Anmeldedaten speichern"
FORGOT_PASSWORD = "Passwort vergessen"
RESET_PASSWORD = "Passwort zurücksetzen"
DATABASE_PATH = "Datenbankpfad"
SPECIFY_LOCATION = "Bestimme den Ort an dem Du Deine Datenbankdateien speichern möchtest."
CURRENT_DIRECTORY = "Aktuelles Verzeichnis"
PARENT_DIRECTORY = "Übergeordnetes Verzeichnis"
SET_DATABASE_LOCATION = "Or für Datenbank wählen"
SET_TIMEZONE = "Zeitzone wählen"
DONT_WORRY = "Keine Sorge, deine Datenbank ist noch hier. Benutze einfach den gleichen Ort an dem sie sich befindet."
SAVE_LOCATION = "Ort speichern"
TIME_TO_LOGIN = "Jetzt wo du einen Admin-Account erstellt hast, wird es Zeit zu unterschreiben und ein paar Tabs zu erstellen..."
AWESOME = "Affengeil!"
REGISTER = "Registrieren"
CREATE_ADMIN = "Admin erstellen"
CREATE_ACCOUNT = "Erstelle einen Account mit Admin-Zugriff"
SETTINGS = "Einstellungen"
UPLOAD_ICONS = "Icons hochladen"
VIEW_ICONS = "Icons anschauen"
ALL_ICONS = "Alle Icons"
CLICK_ICON = "Klicke auf das Icon, um den Pfad in die Zwischenablage zu kopieren"
TABS = "Tabs"
TYPE_HIT_ENTER = "Füge einen neuen TAB-Namen ein und drücke ENTER"
ACTIVE = "Aktiv"
GUEST = "Gast"
NO_IFRAME = "Kein iFrame"
OR = "ODER"
DEFAULT = "Default"
NEW_TAB_NAME = "Neuer Tab-Name"
TAB_URL = "Tab URL"
ICON_URL = "Icon URL"
SAVE_TABS = "Tabs speichern"
CHOOSE_THEME = "Theme wählen"
SAVE_OPTIONS = "Optionen speichern"
TITLE = "Titel"
TITLE_TEXT = "Titeltext"
NAVIGATION_BARS = "Navigations Balken"
TOP_BAR = "Oberer Balken"
BOTTOM_BAR = "Unterer Balken"
SIDE_BAR = "Seitlicher Balken"
HOVER_BG = "Hover Hintergrund"
ACTIVE_TAB = "Aktiver Tab"
ACTIVE_TAB_BG = "Aktiver Tab HG"
ACTIVE_TAB_ICON = "Aktives Tab Icon"
ACTIVE_TAB_TEXT = "Aktiver Tab Text"
INACTIVE_TAB = "Inaktiver Tab"
INACTIVE_ICON = "Inaktives Icon"
INACTIVE_TEXT = "Inaktiver Text"
LOGIN_STATUS = "Login Status"
LAST_SEEN = "Zu letzt angesehen"
USER_GROUP = "Benutzer Gruppe"
USER_ACTIONS = "Benutzer Aktionen"
DELETE = "Löschen"
LOGGED_IN = "Eingeloggt"
LOGGED_OUT = "Ausgeloggt"
GOOD_LOGINS = "Erfolgreiche Logins"
BAD_LOGINS = "Fehlgeschlagene Logins"
DATE = "Datum"
IP_ADDRESS = "IP Addresse"
TYPE = "Typ"
NOTHING_LOG = "Nichts in Log..........."
PURGE_LOG = "Log löschen"
LOGO_URL_TITLE = "Logo-URL für Titel"
LOADING_ICON_URL = "Lade Icon URL"
ABOUT = "Über"
INSTALLED_VERSION = "Installierte Version"
CURRENT_VERSION = "Aktuelle Version"
DELETE_DATABASE = "Datenbank löschen"
DELETE_WARNING = "Tue dies nur wenn ein Upgrade dies vorraussetzt. Dadurch wird deine datenbank gelöscht, es gibt also kein zurück mehr und du musst alles neu anlegen, inklusive Benutzer-Accounts."
SUBMIT_ISSUE = "Problem melden oder Anfrage senden"
VIEW_ON_GITHUB = "Auf GitHub ansehen"
CHAT_WITH_US = "Chatte mit uns"
TABS_SAVED = "Tabs gespeichert!"
APPLY_CHANGES = "Änderungen annehmen"
APPLY_RELOAD = "Änderungen annehmen, um die Seite neu zu laden!"
OK = "OK"
COLORS_SAVED = "Farben gespeichert!"
NEW_VERSION = "Neue Version verfügbar"
CLICK_INFO = "Klicke auf den Info Tab"
WHATS_NEW = "Was ist neu in"
CHANGES = "Änderungen"
AUTO_UPGRADE = "Auto Upgrade"
SOFTWARE_IS = "Software ist"
UP_TO_DATE = "Up-to-date!"
```

**Comment by rix1337** [comment]
This is well done, with typos however. 

I can proofread/merge the files if you want.

**Comment by rix1337** [comment]
Also not entirely translated, but I like the tone.

**Comment by causefx** [comment]
yes please merge them.  I would like to have it as accurate as we can.  Also include PREVIOUS and NEXT at the bottom please.

**Comment by rix1337** [comment]
I proofread the whole file:
I took some ideas of the reddit file, and incorporated them (for accuracy). There were however typos, vernacular and English leftovers. I feel confident in the current commit.

At the bottom I have added all strings required for the log page. Those variables are placeholders; dunno how you want to use them.

**Pull request merged**
