### PR TITLE
Emby invites

### PR DESCRIPTION
**Pull request by noah-witt**
Emby Invites, a first attempt at implementation. I am not well versed in PHP. I would imagine that this will take some cleaning up and work particularly with step 4 of the invite process. 

There is an issue with the UI code. When it loads the JSON configuration for the emby settings the server returns the correct JSON but the html generator just prints the first {.

### CODE REVIEW

**Comment by causefx** [comment]
Looks good so far, from a quick glance... I would change both:

$GLOBALS['INVITES-embyApiKey']
$GLOBALS['INVITES-embyAddress']
to
$GLOBALS['embyToken']
$GLOBALS['embyURL']

so we dont have multiple values....

**Comment by noah-witt** [comment]
This is working in my testing environment right now. It is working but there are some issues that I need help with before I would consider this production ready.

- The javascript that converts the JSON array of settings to a menu fails when given text with JSON inside. Whoever wrote that code should be able to fix these issues relatively easily. I do not think it is reasonable to build a UI that allows for configuring all the options that every sysadmin would want. One option would be specifying a template user that will have its config copied from but that would require some serious JSON manipulation on our part.  In Issue #1124 I provide examples of the JSON that users are currently expected to write.

 -  The email the user specifies will not end up attached to the user's Organizer profile. The solution to this would be to trigger the user import into Organizer when the user is created and update the user profile with their email.

 - A third and lower priority upgrade that would be good for plex too would be if Ombi import was triggered on user creation and their email updated with the correct email entered on account creation. 

 - I do not have the infrastructure to test plex invites so someone, who has a functional plex server, should test to make sure I did not break plex invites in any way.

**Comment by causefx** [comment]
I will merge with my dev instance and test out.

**Comment by causefx** [comment]
Confirming that Plex Invites still works fine

**Comment by causefx** [comment]
I just installed Emby to test....

Looks like it created an emby user on the invite side....  I will look at the code to give users the library 

image

**Comment by noah-witt** [comment]
I was trying to reproduce the bug and found that it seems to only happen for me when I change to plex and do not reload before creating the invite code which appears to be passed to the web browser on load of the page and then passed back to the server when the invite code is created.

**Pull request merged**
