### PR TITLE
Apple homescreen icon

### PR DESCRIPTION
**Pull request by Yann-J**
This is a small suggested change to the HTML metas to improve the experience saving the shortcut as a homescreen icon.

I know some of these can be passed into the favicon section through the UI, but I think they deserve to be automatic.

The favicon section still needs some fiddling to pass the appropriate icon and splash screen images.

### CODE REVIEW

**Comment by causefx** [comment]
nice. i like it lol.
you reverted the JWT change? no longer needed?

**Comment by Yann-J** [comment]
JWT change is still there, just a different PR to keep things separate :)

**Comment by causefx** [comment]
the other commit is bringing back the older config changes.

**Comment by Yann-J** [comment]
Hmm you're right, not sure what happened here. I've restored the changes.
Note I've also reverted a change that inadvertently updated a regex (my editor was automatically replacing some unicode quotes into straight quotes...). You might want to check that it's correct.

**Pull request merged**
