### PR TITLE
Allow empty password for Deluge

### PR DESCRIPTION
**Pull request by d-lindahl**
My use case: I have Deluge behind oauth2 proxy and Organizr accesses it using internal docker network so I set a blank password to avoid double login.

### CODE REVIEW

**Comment by causefx** [comment]
it still pulls the data without the password set in deluge?  last we checked it broke using the class we included...

**Comment by d-lindahl** [comment]
That's why. I thought it was a bit weird to not allow empty. Pulls data for me without problems, Deluge version 2.0.3 and WebAPI-0.4.0.

**Comment by d-lindahl** [comment]
I can add a warning about it (and also clean up some now unused strings that I missed)

**Comment by d-lindahl** [comment]
Seems it worked until Deluge was restarted and then the password gets reset to the default. Looks like keeping it not empty is still a good idea :(

**Comment by d-lindahl** [comment]
After some more testing that was apparently something else going weird 🙃 I'll go with adding a warning if that's alright with you @causefx !

**Comment by causefx** [comment]
yeah add what is needed and I will test this weekend.

**Comment by d-lindahl** [comment]
Simply added a help text and a notice on the test connection tab

**Pull request merged**
