### PR TITLE
Enforce https

### PR DESCRIPTION
**Pull request by Miicker**
Could you guys please make an option that enforces the use of https?
Now I have to edit index.php after an update and add this code:

`if($_SERVER["HTTPS"] != "on")
{
    header("Location: https://" . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"]);
    exit();
}`

Perhaps you can make an option which enables this code if the option is checked?
Thanks!

### CODE REVIEW

**Comment by causefx** [comment]
we can certainly do this but why wouldn't you just do this on your webserver?

**Comment by Miicker** [comment]
How should I do this on my webserver? I host Organizr on my Synology NAS, which gives me the option to use SSL, but there is no option to redirect all traffic to SSL (especially because I also run some non-https services).

**Comment by causefx** [comment]
let me read up on Synology webservers, but for Apache and Nginx, you would forward all traffic on port 80 to 443.  Basically anything coming through to http://example.com/test would forward to https://example.com/test

From what I read on a quick search is that Synology run Apache... place a `.htaccess` file in the root of your document folder.  That file should have:

```
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
```

**Comment by benbar21** [comment]
@Miicker Just make a .htaccess file like @causefx mentioned. Or if you're running your site through cloudflare you can enforce https only with a page rule.

**Comment by nkean** [comment]
Also running on a Synology.  To force Organizr webpage to use https, take a look at virtual hosts.  To cause all your other services to use https: Control Panel > Network > DSM Settings and check top box "Automatically redirect HTTP connections to HTTPS"

**Comment by causefx** [comment]
@benbar21 wanna test something out?

**Comment by benbar21** [comment]
@causefx  sorry I didn't see this till now! Not sure why it didn't show up in my git notifications

what's up?

**Comment by causefx** [comment]
All good. I already released what I was going to have u test

**Pull request closed without merging**
