### PR TITLE
Develop

### LINKED ISSUE #42: [Feature request] go directly to a tab
Sorry if I explain this poorly!

Say I have two tabs: Plex and Ombi. Plex is the default tab. It'd be great if I could somehow go directly to Ombi by going to domain.com/ombi or domain.com#ombi, for example. 

I'm not sure how hard this'd be to add, but it would be really useful!

### LINKED ISSUE #44: Cannot create admin
So i'm on the screen after providing a database location and I cannot create an admin user.

I fill in the username, email and both passwords, press the register button and nothing happens.

Nothing in the console, no requests are being sent when pressing register 😢

### PR DESCRIPTION
**Pull request by causefx**
<br>Fixed #42 - Added Quick Access to tabs by using tab name in URL.  i.e. #Sonarr 
<br>Fixed #44 - Fixed Registration button to allow click and Enter to submit.
<br>Fixed view all icons
<br>Fixed Tab issue on movement in settings
<br>Fixed mobile scroll on list
<br>Added more icons.
<br>Added modal for Add to Homescreen 
<br>Made app fullscreen when added to homescreen
<br>Added image to loading screen

### CODE REVIEW

**Comment by benbar21** [comment]
The image seems kind of off, when it appears with the other loading animation. 

Let me know if you want me to explain more!

**Comment by causefx** [comment]
reset your cache.  it needs to refresh the CSS.

**Comment by benbar21** [comment]
I have! Having the loading animation over the static logo just seems somewhat off to me?

**Comment by causefx** [comment]
ahhhhh, now I understand.  I will be putting an option to turn it off in the future if you dont like it.

**Comment by benbar21** [comment]
Great, thanks!

**Pull request merged**
