### PR TITLE
Fixes and Features added

### LINKED ISSUE #25: Option to add a logo on the top bar
Hi, I've got a request for a small cosmetic change, could you please add an option to add a logo in the center of the top bar?

I can do that at the moment by adding the html tags in the title field in settings, it almost works perfectly but it obviously displays the html tags text on the browser title bar. See the screenshot below. 

It's not urgent.

Thanks 

image

### LINKED ISSUE #40: [Feature Request] Option to change the loading icon
As discussed, could you please add an option change the loading icon?

image

### LINKED ISSUE #57: Set Timezone default is broken, filled with warning instead of example.
Starting with fresh git install, the 'Set Timezone' default box is filled with the text below:

> `<br /><b>Warning</b>:  : It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/var/www/organizr/index.php</b> on line <b>667</b><br />UTCdate_default_timezone_get()`

### PR DESCRIPTION
**Pull request by causefx**
Fixed #25 - Added option to have logo in title bar - Image has to be 250px on width and 50px on height
Fixed #40 - Added option to change the loading icon
Fixed #57 - Timezone error on older php

### CODE REVIEW

**Comment by rix1337** [comment]
**Bug** title stays uncolored, now. At least it's white for me..

**Comment by causefx** [comment]
can you clarify a little more?  or Screenshot?

**Comment by rix1337** [comment]
There you go. The css color is not active..
bug

**Comment by causefx** [comment]
yup, good catch, ` echo "<span><span style=\"color: topbartext\"><b>$title</b></span></span>";`

Forgot the `$`

**Pull request merged**
