### PR TITLE
Added Pi-hole homepage item

### PR DESCRIPTION
**Pull request by henrywhitaker3**
Added a pihole homepage item addressing issue #1277

### CODE REVIEW

**Comment by causefx** [comment]
There's a few things we still need to add - want me to list or fix them?

**Comment by henrywhitaker3** [comment]
Yeah happy to help out if u want

**Comment by causefx** [comment]
any reason you went this route:
`substr($url, 7, -16)`

**Comment by henrywhitaker3** [comment]
Looks a bit nicer on the front-end to differentiate between servers:

`http://10.0.0.2/admin` vs `10.0.0.2`

Suppose it would fail with https though, using regex to grab the IP address instead would be better. Can push a commit with that now if you want?

**Comment by causefx** [comment]
take a look at function `qualifyURL` 
use that to return the host.

`$host = qualifyURL($url, true)['host'];`
that should work.

**Comment by causefx** [comment]
Now all that is left is to add to homepage sort function and check if hostname/ip is used already.  Want me to take care of that?

**Comment by henrywhitaker3** [comment]
For homepage sort, do you mean adding to `buildHomepageSettings()` in `homepage-functions.php`? And checking the IP against what?

**Comment by causefx** [comment]
yes, we need to add the few lines to add to that list.  

disregard the ip line :)

**Comment by henrywhitaker3** [comment]
Sound, that should be done

**Comment by henrywhitaker3** [comment]
Yeah should be pretty easy, will have a look at it now

EDIT: Have created a PR ( #1342) with this added

**Comment by jscottelblein** [comment]
Great widget so far. 

One nice enhancement would be to add an on/off toggle to each Pi-hole widget, to quickly disable/enable PH right from the homepage.

There's a pretty nice Chrome extension that does this, which might make it real easy to just put the code into the widget (and then gussy it up to match the widget ;) ):

https://github.com/Spencer-Yoder/Remote-Switch-for-Pi-Hole-Chrome

https://chrome.google.com/webstore/detail/remote-switch-for-pi-hole/nkkklnmkpmobgcbkipccdjahpcgbhnki?hl=en

Maybe put the toggle button right next to the label on each PH?

**Comment by jscottelblein** [comment]
I made a small tweak to the "merged" widget that I thought I'd share, just in case ya wanted to add it as a default tweak. It's a light line between the 2 PH stats, so that it looks like this (you'll have to click the image to see it; the shrunken down version makes it too hard or impossible to see):

image

I just whipped it up super quick and haven't gone through and perfected it, so you might want to. Currently, if you hover your cursor over the line, a strange effect happens (bouncy effect). You'll see it if you test out the tweak.

I just added this to the custom CSS in Organizr:

```
/* Pi-Hole widget */
#allPihole > div > div > div > div:nth-child(n) > div > div > div > h3:nth-child(n) {
    border-top: 1px solid #ffffff6b;
    padding-top: 8px;
}
```

**Comment by jscottelblein** [comment]
Another enhancement idea: when using the merged widget, it might be visually more friendly to add some sort of placeholder (i.e. dashes or something) where the stats would be, and then replace them with the stats.

Currently I'm noticing a bit of an annoying page bounce when one of the piholes is taking too long during a refresh or something, as the widget changes size when it thinks one of them isn't there anymore, and then resizes as it re-adds it. With so many refreshes these page bounces happens quite often. 

If there are for example, 3 PH urls in the widget's settings, we know the size the widget is supposed to be, so whether the PH is available or not, the widget wouldn't have to keep resizing, and if it's data isn't available there could just be a dash in place of it's stats, to denote it's offline.

**Comment by jscottelblein** [comment]
Just curious if this is happening to anyone else? Suddenly the widget stopped working if you have more than 1 PH in the list.

For example, if I use this (I'm currently using/testing 3 PH's on 3 diff devices in a swarm):

    http://pihole/admin,http://192.168.0.78/admin,http://192.168.0.131/admin

and test the connection, the first one tests OK while the last 2 fail. The last 2 failing is currently expected because I haven't re-added them to my swarm yet and have the devices turned off, but the first one succeeds and then I go to the home page and the PH widget doesn't show at all.

Then, if I do:

    http://pihole/admin

the test succeeds and the PH widget shows fine on the homepage. I've also tried switching out the `pihole` for the direct IP `192.168.0.194` but the results are the same in all cases. (on docker I tend to prefer to let docker do all the dns resolving rather than hardcoding in the IPs)

Previously, the widget worked with that exact first line of multiple PH's and if on of the PH's when down the widget still showed, it just didn't add the info from the PH(s) that were down.

Currently using Organizr 2.1.0 Dev

**Comment by spupuz** [comment]
can't get it work dunno why it says that it can't connect to pi hole

image


but the host is perfectly reachable

image

**Comment by jscottelblein** [comment]
Can't tell by the screenshot, but if you're not already using it, try using `http://192.168.1.53/admin` as the URL to connect to in the widget. (i.e. don't forget to add the `/admin` to the end.)

**Comment by spupuz** [comment]
I'm already using it, is there a log I can provide?

**Comment by spupuz** [comment]
i suppose that my problem is related to the fact that using mcvlan for pihole on same system so other docker could not comunicate correctly

**Pull request merged**
