### PR TITLE
Develop

### LINKED ISSUE #54: Configurable timezone
I just noticed for #41 to work the timezone has to be configurable.. currently it's hard coded to LA 

Any chance you could move this to the database?

### LINKED ISSUE #55: [Feature Request] Option to sort the the login log
As discussed could you add an option sort the login log table?

### PR DESCRIPTION
**Pull request by causefx**
Fixed #54 - Fixed Timezone to be set, delete databaseLocation.ini.php to set it up
Fixed #55 - Added sort option to Login Log
Improvements - Changed Icon view again to make it pretty.  Various css improvement throughout.

### CODE REVIEW

**Comment by rix1337** [comment]
This is amazing! Fail2ban works now.

I will create a shirt demonstration.

Enter wrong login info 3 times and you are outhe for 15 minutes on my server!

**Comment by causefx** [comment]
sweet! i'll await the demo

**Comment by rix1337** [comment]
It's harder to capture than i thought, because of how I set up caching on my server, once you are banned it takes a while for the timeout to appear. But i'll get to it!

**Comment by causefx** [comment]
lol, no worries.

**Pull request merged**
